name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            artifact_name: keyremap.exe
            asset_name: keyremap-windows-amd64

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build
        run: cargo build --release
        
      - name: Create version-specific zip
        run: |
          dir target\release
          mkdir release
          copy target\release\keyremap.exe release\
          dir release
          7z a keyremap-${{ github.ref_name }}-windows-amd64.zip .\release\keyremap.exe
          dir
        shell: cmd
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: keyremap-${{ github.ref_name }}-windows-amd64.zip
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: |
            artifacts/keyremap-windows-amd64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
